# Generated by Django 5.1.2 on 2024-11-25 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
